# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/teacher/*"
  to = "/teacher/index.html"
  status = 200

[[redirects]]
  from = "/student/*"
  to = "/student/index.html"
  status = 200